apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
  labels:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
type: Opaque
data:
  mssql_sa_password : {{ .Values.MSSQL_SA_PASSWORD | b64enc | quote}}
