apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sql-server-rancher.fullname" . }}
  labels:
    {{- include "sql-server-rancher.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "sql-server-rancher.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "sql-server-rancher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sql-server-rancher.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/bash
            - -c
            - /opt/mssql/bin/sqlservr
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.ports.containerPort }}
          env:
            # prefer mssql-config over env vars
            - name: MSSQL_PID
              value: {{ index .Values "mssql.pid" }}
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secret
                  key: mssql_sa_password 
          volumeMounts:
            - name: mssql
              mountPath: /var/opt/mssql
            - name: mssql-config
              mountPath: /var/opt/mssql/mssql.conf
              subPath: mssql.conf
      volumes:        
        - name: mssql-config
          configMap:
            name: mssql
  volumeClaimTemplates:
    - metadata:
        name: mssql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 8Gi
        storageClassName: {{ index .Values "storageClass.provisioner" }}
