---

mssql.pid: Developer
mssql.conf.eula.accepteula: true
mssql.conf.eula.accepteulaml: true
mssql.conf.sqlagent.enabled: true

image:
  repository: mcr.microsoft.com/mssql/server
  pullPolicy: IfNotPresent
  tag: 2019-latest

containers:
  ports:
    containerPort: 1433

podAnnotations: {}

podSecurityContext:
  fsGroup: 10001

service:
  port: 1433
